@startuml

class User{
    id:int
    name:varchar
    mail:varchar
    ps:varchar
    answer:varchar
    createdAt:datetime
    updatedAt:datetime
    questionsId:int
}

class Questions{
    id:int
    content:varchar
}

class Result{
    id:int
    myScore:int
    opponentScore:int
    registId:int
    opponentId:int
}

class Match{
        id:int
        varchar match_name
        varchar round
}

class Opponent{
    id:int
   name:varchar
   userId:int
}

class Regist{
    id:int
    matchId:int
    userId:int
}

User"0..*" -le- "1"Questions
User"1" -- "0..*"Opponent
User"1" -ri- "0..*"Regist
Regist"1" -- "1"Match
Regist"1" -- "0..*"Result
Result"0..*" -- "1"Opponent

@enduml